[pytest]
filterwarnings =
    ignore:.*Pyparsing.*deprecated.*:DeprecationWarning
    ignore:.*'oneOf' deprecated.*:DeprecationWarning
    ignore:.*'parseString' deprecated.*:DeprecationWarning
    ignore:.*'resetCache' deprecated.*:DeprecationWarning
    ignore:.*'enablePackrat' deprecated.*:DeprecationWarning
